# Faça um programa que leia algo pelo teclado (input) e mostre na tela o seu tipo primitivo e todas as informações possíveis sobre ele.
n1 = (input('Digite algo: '))
print(type(n1))
print('É alfanumérico?',(n1.isalnum()))
print('É um número?',(n1.isnumeric()))
print('É alfabético?',(n1.isalpha()))
print('É um SCII?',(n1.isascii()))
print('É um dígito?',(n1.isdigit()))
print('É um número decimal?',(n1.isdecimal()))
print('É um identificador?',(n1.isidentifier()))
print('Está em minúsculo?',(n1.islower()))
print('É possível imprimir?',(n1.isprintable()))
print('Só tem espaço?',(n1.isspace()))
print('É um título?',(n1.istitle()))
print('Está em maiúsculo?',(n1.isupper()))